# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snoop < Formula
  desc ""
  homepage "https://github.com/deepraj02/homebrew-taps"
  version "2.0.0"

  on_macos do
    on_intel do
      url "https://github.com/deepraj02/snoop/releases/download/v2.0.0/snoop_Darwin_x86_64.tar.gz"
      sha256 "a663ccf978519fc26ec62528272c92a9f4fa93d1373188e210a478811f9580ad"

      def install
        bin.install "snoop"
      end
    end
    on_arm do
      url "https://github.com/deepraj02/snoop/releases/download/v2.0.0/snoop_Darwin_arm64.tar.gz"
      sha256 "d964b7b112868bb68002e7e04f5e7a87a7c3d9083c6ca7d9e4e810b4ac133807"

      def install
        bin.install "snoop"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deepraj02/snoop/releases/download/v2.0.0/snoop_Linux_x86_64.tar.gz"
        sha256 "219b3a226d3face3a8bea74fe1a5c3399906fd06575ba748e80b65e6f917022f"

        def install
          bin.install "snoop"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deepraj02/snoop/releases/download/v2.0.0/snoop_Linux_arm64.tar.gz"
        sha256 "9508bdefa7c3132adcc1da0fa8bf1872f7dbeea69f4ccdc7133f5e7299f4b5d9"

        def install
          bin.install "snoop"
        end
      end
    end
  end
end
