# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snoop < Formula
  desc ""
  homepage "https://github.com/deepraj02/homebrew-taps"
  version "2.0.1"

  on_macos do
    on_intel do
      url "https://github.com/deepraj02/snoop/releases/download/v2.0.1/snoop_Darwin_x86_64.tar.gz"
      sha256 "8abdd71cdbe5a14702be0d647fc8148437371e48031d53bc4ec55e1e180c5489"

      def install
        bin.install "snoop"
      end
    end
    on_arm do
      url "https://github.com/deepraj02/snoop/releases/download/v2.0.1/snoop_Darwin_arm64.tar.gz"
      sha256 "d31255a06c0153839c8f148767d35d1fb9c8f050c171a6eb30ca39822fad3e73"

      def install
        bin.install "snoop"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deepraj02/snoop/releases/download/v2.0.1/snoop_Linux_x86_64.tar.gz"
        sha256 "f1a8f62a88b07cc9a95210106adfa4797e673db7570d05e94047ab70ea254f83"

        def install
          bin.install "snoop"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deepraj02/snoop/releases/download/v2.0.1/snoop_Linux_arm64.tar.gz"
        sha256 "93beaef6ed2e56eea0591c555dc05c96c8a98cb79aa8e4aceec342abefd932c7"

        def install
          bin.install "snoop"
        end
      end
    end
  end
end
