# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snoop < Formula
  desc ""
  homepage "https://github.com/deepraj02/homebrew-taps"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/deepraj02/snoop/releases/download/v1.0.0/snoop_Darwin_x86_64.tar.gz"
      sha256 "5913e1f2e762155fbffc886105c1523fb3fd3675fa8a8890c0dbc2802ea3f252"

      def install
        bin.install "snoop"
      end
    end
    on_arm do
      url "https://github.com/deepraj02/snoop/releases/download/v1.0.0/snoop_Darwin_arm64.tar.gz"
      sha256 "5d1ba5683e3dc912d91de36805ce7922abe05e392d079dc0cef1fb1c63d82649"

      def install
        bin.install "snoop"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deepraj02/snoop/releases/download/v1.0.0/snoop_Linux_x86_64.tar.gz"
        sha256 "70c102e3eeeac1b35472958ef7d64d704a8f2cd08555cf626b6881c3c8973f38"

        def install
          bin.install "snoop"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deepraj02/snoop/releases/download/v1.0.0/snoop_Linux_arm64.tar.gz"
        sha256 "b0e678bb2f46a41bc235f69a0b805815c8cb3a439849724aaa62def80deec9ac"

        def install
          bin.install "snoop"
        end
      end
    end
  end
end
